name: sms_firebase
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  collection: ^1.17.1
  country_code_picker: ^3.0.0
  country_codes: ^3.2.2+3
  dotted_line: ^3.2.2
  equatable: ^2.0.5

  # ↓↓↓ Versión compatible con Flutter + Firebase Core 2.x ↓↓↓
  file_picker: ^8.0.7

  # ↓↓↓ Firebase 2.x (tu serie actual) ↓↓↓
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.0
  firebase_messaging: ^14.9.4

  # ↓↓↓ Versión compatible con Firebase Core 2.x ↓↓↓
  firebase_app_check: ^0.2.2+3

  flutter_local_notifications: ^19.4.0
  google_maps_flutter: ^2.3.0
  permission_handler: ^10.4.0
  flutter_polyline_points: ^3.0.1
  geolocator: ^10.1.1
  google_places_flutter: ^2.1.1
  http: ^1.2.1
  flutter_bloc: ^9.0.0
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.9
  flutter_map: ^5.0.0
  flutter_map_animations: ^0.4.1
  #flutter_map_location_marker: ^7.0.2
  flutter_native_splash: 2.3.8
  flutter_svg: ^2.0.7
  flutter_vector_icons: ^2.0.0

  google_fonts: ^5.1.0

  graphql_flutter: ^5.2.0-beta.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  intl: ^0.19.0
  json_annotation: ">=4.8.0"
  latlong2: ^0.9.0
  lifecycle: ^0.9.0
  map_launcher: ^3.5.0
  meta: ^1.3.0
  modal_bottom_sheet: 3.0.0-pre
  package_info_plus: ^8.2.0
  pinput: ^5.0.1
  shimmer: ^3.0.0
  timeago_flutter: ^3.5.0
  url_launcher: ^6.1.12
  maps_toolkit: ^3.1.0
    #flutter_hooks: ^0.18.5
  flutter_map_location_marker: ^7.0.0
  flutter_ringtone_player: ^4.0.0+4
  client_shared:
    path: ../libs/client-shared
  flutter_gen: ^5.12.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  build_runner: ^2.4.5
  flutter_gen_runner: ^5.3.1
  json_serializable: ^6.2.0
  graphql_codegen: ^1.1.1
  flutter_launcher_icons: ^0.14.3
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - ionicons/
    - google_fonts/
flutter_intl:
  enabled: true
flutter_gen:
  integrations:
    flutter_svg: true
